language: go

go:
 - 1.2
 - 1.3
 - release
 - tip

script:
 - go fmt ./...
 - go vet ./...
 - go test -v ./...
 - go build -v ./...

install:
 - go get github.com/spf13/viper
 - go get github.com/ngdinhtoan/go-jira-client
 - go get github.com/stretchr/testify
